name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Install wait-on
        run: pnpm add -D wait-on

      - name: Start Vite preview (background)
        run: |
          pnpm run preview -- --port 5000 &
          npx wait-on http://localhost:5000/popup.html

      - name: Run smoke tests
        run: pnpm test:e2e

      - name: Run unit tests
        run: pnpm test:unit
